-- 초기 스키마.
--
-- ddl-auto: update 로 만들어진 현재 스키마를 pg_dump 로 뽑아 고정한 것이다.
-- Hibernate 가 생성한 해시 제약 이름(uk64htm6...)은 읽을 수 없어 의미 있는 이름으로 바꿨다.
--
-- 이후 스키마 변경은 전부 새 마이그레이션 파일로 남긴다. ddl-auto 는 validate 다.

-- 카카오 회원번호로만 식별한다. 이름·나이·성별은 health_profiles 에 둔다.
CREATE TABLE users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kakao_id   BIGINT      NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_users_kakao_id UNIQUE (kakao_id)
);

-- 로그인 수단이 아니라 푸시 대상이다. user 1 : device N.
CREATE TABLE devices (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL,
    push_token   VARCHAR(512) NOT NULL,
    platform     VARCHAR(16)  NOT NULL,
    last_seen_at TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uk_devices_push_token UNIQUE (push_token),
    CONSTRAINT fk_devices_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_devices_platform CHECK (platform IN ('ANDROID', 'IOS'))
);

-- 원문이 아니라 해시를 저장한다. DB 가 유출돼도 그것만으로 로그인되지 않게.
CREATE TABLE refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    CONSTRAINT uk_refresh_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- 온보딩에서 받는 환자 정보. 화면 S1.
--
-- *_status 는 세 값이다. NONE("없어요")과 UNKNOWN("잘 모르겠어요")을 구분해야
-- 의사용 카드에 "알레르기: 본인 확인 못 함"을 찍을 수 있다.
--
-- *_source 는 값의 출처다. 사용자가 고친 값(SELF_INPUT)을 다음 로그인 때
-- 카카오 값으로 덮어쓰지 않기 위해 남긴다.
CREATE TABLE health_profiles (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT      NOT NULL,

    name               VARCHAR(255),
    name_source        VARCHAR(16),
    birth_year         INTEGER,
    birth_year_source  VARCHAR(16),
    birth_month_day    VARCHAR(5),
    sex                VARCHAR(16),
    sex_source         VARCHAR(16),

    medications_status VARCHAR(16),
    conditions_status  VARCHAR(16),
    allergies          VARCHAR(255),
    allergies_status   VARCHAR(16),

    completed_at       TIMESTAMPTZ,
    created_at         TIMESTAMPTZ NOT NULL,
    updated_at         TIMESTAMPTZ,

    CONSTRAINT uk_health_profiles_user UNIQUE (user_id),
    CONSTRAINT fk_health_profiles_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_health_profiles_sex CHECK (sex IN ('FEMALE', 'MALE', 'UNSPECIFIED')),
    CONSTRAINT ck_health_profiles_name_source CHECK (name_source IN ('KAKAO', 'SELF_INPUT')),
    CONSTRAINT ck_health_profiles_birth_year_source CHECK (birth_year_source IN ('KAKAO', 'SELF_INPUT')),
    CONSTRAINT ck_health_profiles_sex_source CHECK (sex_source IN ('KAKAO', 'SELF_INPUT')),
    CONSTRAINT ck_health_profiles_medications_status CHECK (medications_status IN ('KNOWN', 'NONE', 'UNKNOWN')),
    CONSTRAINT ck_health_profiles_conditions_status CHECK (conditions_status IN ('KNOWN', 'NONE', 'UNKNOWN')),
    CONSTRAINT ck_health_profiles_allergies_status CHECK (allergies_status IN ('KNOWN', 'NONE', 'UNKNOWN'))
);

CREATE TABLE health_profile_medications (
    profile_id BIGINT       NOT NULL,
    item       VARCHAR(255) NOT NULL,
    CONSTRAINT fk_health_profile_medications_profile
        FOREIGN KEY (profile_id) REFERENCES health_profiles (id)
);

CREATE TABLE health_profile_conditions (
    profile_id BIGINT       NOT NULL,
    item       VARCHAR(255) NOT NULL,
    CONSTRAINT fk_health_profile_conditions_profile
        FOREIGN KEY (profile_id) REFERENCES health_profiles (id)
);

-- 조회 패턴에 맞춘 인덱스. 유니크 제약이 있는 컬럼은 이미 인덱스가 생기므로 제외한다.
CREATE INDEX idx_devices_user ON devices (user_id);
CREATE INDEX idx_refresh_tokens_user ON refresh_tokens (user_id);
CREATE INDEX idx_health_profile_medications_profile ON health_profile_medications (profile_id);
CREATE INDEX idx_health_profile_conditions_profile ON health_profile_conditions (profile_id);
