-- 문답 턴의 감사 기록.
--
-- **한시입니다.** AI 트랙이 회귀 eval 케이스를 채우려고 실사용 발화를 받습니다
-- (Medical-Mate/AI#113). 심사가 끝나고 내보내기 파일을 넘긴 뒤에는
-- **이 테이블을 지웁니다** — 안 지우면 발화가 영영 남습니다.
--
-- **앱 경로만입니다.** 웹 데모는 "증상 내용을 저장하지 않는다" 를 README·Swagger·
-- 소개 화면 셋에 적어 두었고, 고지를 바꾸는 것이 먼저라 여기 안 들어옵니다.
--
-- 앱은 다릅니다 — intake_messages 에 이미 발화를 저장하고 있습니다. 계정이 있고
-- 문답을 이어서 할 수 있어야 해서입니다. audit 은 **새 정보가 아니라 이미 있는 것의
-- 다른 모양**이라 여기서는 증분입니다.
CREATE TABLE intake_turn_audits (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    session_id BIGINT      NOT NULL,

    -- 몇 번째 턴인가. intake_messages 와 같은 축이라 나중에 발화와 맞춰 볼 수 있다.
    seq        INTEGER     NOT NULL,

    -- **열어보지 않는다.** 물은 축 · LLM 에 들어간 발화 · 모델 원본 추출 · 가드
    -- 통과분 · 버린 것 · usage 가 들어 있고, 구조는 AI 계약이 정한다. 우리가 읽기
    -- 시작하면 저쪽 변경이 우리를 깨뜨린다.
    audit      JSONB       NOT NULL,

    created_at TIMESTAMPTZ NOT NULL,

    -- 세션의 자식이다. 탈퇴가 세션을 지우면 이것도 같이 사라진다.
    CONSTRAINT fk_intake_turn_audits_session
        FOREIGN KEY (session_id) REFERENCES intake_sessions (id),
    CONSTRAINT uk_intake_turn_audits_session_seq UNIQUE (session_id, seq)
);

CREATE INDEX idx_intake_turn_audits_session ON intake_turn_audits (session_id);

COMMENT ON TABLE intake_turn_audits IS
    'AI 회귀 eval 재료. 심사 종료 후 내보내고 나면 테이블째 지운다.';
