-- 진료 후 메모 분류의 감사 기록.
--
-- **한시입니다.** AI 트랙이 회귀 eval 케이스를 채우려고 실사용 메모를 받습니다
-- (Medical-Mate/AI#113). 심사가 끝나고 내보내기 파일을 넘긴 뒤에는
-- **이 테이블을 지웁니다** — 안 지우면 메모가 영영 남습니다.
--
-- **앱 경로만입니다.** 웹 데모는 고지를 바꾸는 것이 먼저라 여기 안 들어옵니다.
--
-- **회원 직속입니다.** intake_turn_audits 는 세션의 자식인데 이건 부모가 없습니다 —
-- POST /api/visits/classify 는 미리보기라 그 시점에 visit_records 행이 아직
-- 없습니다. 그래서 탈퇴 삭제를 AuthService.deleteAllData 가 직접 합니다.
--
-- **저장 범위가 넓어집니다.** 지금까지는 환자가 저장을 눌러야 메모가 남았는데,
-- 정리만 해 보고 나간 메모도 여기 남습니다. 문답 쪽과 같은 성질이고(하다 나가도
-- 턴이 남습니다), 그래서 심사 종료 시 드롭이 더 중요합니다.
CREATE TABLE visit_memo_audits (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id    BIGINT      NOT NULL,

    -- 누가 라벨을 붙였나. server = 모델이 붙임 · client = 환자가 고친 것을 되보냄 ·
    -- none = 문장만 나눔. 앱이 메모 한 건에 classify 를 두 번 이상 부르므로 한 메모가
    -- 여러 행이 된다. **거르는 것은 내보낼 때** 한다 — client 가 곧 정답 라벨이라
    -- 저장 시점에 버리면 eval 에 제일 값어치 있는 쪽이 사라진다.
    source     VARCHAR(16),

    -- **열어보지 않는다.** 메모 원문 · 나눈 문장 · 붙은 라벨 · 모델 원본 출력 ·
    -- 버린 것 · usage 가 들어 있고, 구조는 AI 계약이 정한다. 우리가 읽기 시작하면
    -- 저쪽 변경이 우리를 깨뜨린다.
    audit      JSONB       NOT NULL,

    created_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_visit_memo_audits_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_visit_memo_audits_user ON visit_memo_audits (user_id);

COMMENT ON TABLE visit_memo_audits IS
    'AI 회귀 eval 재료. 심사 종료 후 내보내고 나면 테이블째 지운다.';
