-- 문답 세션(S1.5·S2)과 브리핑 카드(S3).

-- 시작 부위와 진행도를 들고 있는 이유는 앱을 껐다 켜도 이어져야 하기 때문이다.
CREATE TABLE intake_sessions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT      NOT NULL,
    status           VARCHAR(16) NOT NULL,
    site_text        VARCHAR(100),
    progress_current INTEGER     NOT NULL DEFAULT 0,
    progress_total   INTEGER     NOT NULL DEFAULT 6,
    started_at       TIMESTAMPTZ NOT NULL,
    completed_at     TIMESTAMPTZ,
    CONSTRAINT fk_intake_sessions_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_intake_sessions_status CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'ABANDONED'))
);

-- 부위 마스터는 아직 없다. 코드 대조는 마스터가 생길 때(S1.5) 붙인다.
CREATE TABLE intake_session_sites (
    session_id BIGINT      NOT NULL,
    site_code  VARCHAR(64) NOT NULL,
    CONSTRAINT fk_intake_session_sites_session
        FOREIGN KEY (session_id) REFERENCES intake_sessions (id)
);

-- seq 는 카드의 evidence 가 참조하는 번호다.
-- 본문은 증상 텍스트라 민감정보다.
CREATE TABLE intake_messages (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   BIGINT        NOT NULL,
    seq          INTEGER       NOT NULL,
    role         VARCHAR(8)    NOT NULL,
    text         VARCHAR(2000) NOT NULL,
    input_method VARCHAR(8),
    created_at   TIMESTAMPTZ   NOT NULL,
    CONSTRAINT fk_intake_messages_session
        FOREIGN KEY (session_id) REFERENCES intake_sessions (id),
    CONSTRAINT uk_intake_messages_session_seq UNIQUE (session_id, seq),
    CONSTRAINT ck_intake_messages_role CHECK (role IN ('AI', 'USER')),
    CONSTRAINT ck_intake_messages_input_method CHECK (input_method IN ('TEXT', 'STT'))
);

-- 브리핑 카드.
--
-- 환자 인적사항(patient_*)은 만든 시점 값을 박아둔다. 프로필을 참조하면 나중에
-- 이름을 고쳤을 때 이미 확정된 카드까지 바뀐다. 의사가 본 카드는 그대로 남아야 한다.
--
-- 확정 이후의 변경은 이 행을 고치지 않고 새 행을 만든다.
-- version 과 parent_card_id 로 체인이 된다.
--
-- 목록·중첩 구조(medications·questions·evidence·site_codes)는 jsonb 다.
-- AI 응답이라 구조가 흔들릴 수 있어 테이블로 쪼개지 않는다.
CREATE TABLE briefing_cards (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT      NOT NULL,
    session_id           BIGINT      NOT NULL,

    status               VARCHAR(16) NOT NULL,
    version              INTEGER     NOT NULL DEFAULT 1,
    parent_card_id       BIGINT,

    patient_name         VARCHAR(30),
    patient_age          INTEGER,
    patient_sex          VARCHAR(16),

    title                VARCHAR(20) NOT NULL,

    onset_status         VARCHAR(16) NOT NULL,
    onset_text           VARCHAR(80),
    pattern_status       VARCHAR(16) NOT NULL,
    pattern_text         VARCHAR(80),
    site_status          VARCHAR(16) NOT NULL,
    site_text            VARCHAR(80),
    site_codes           JSONB,
    medications_status   VARCHAR(16) NOT NULL,
    medications          JSONB,
    allergies_status     VARCHAR(16) NOT NULL,
    allergies_text       VARCHAR(80),
    questions            JSONB,
    suggested_department VARCHAR(32),
    evidence             JSONB,

    pipeline_version     VARCHAR(64),
    ai_request_id        VARCHAR(64),

    created_at           TIMESTAMPTZ NOT NULL,
    confirmed_at         TIMESTAMPTZ,

    CONSTRAINT fk_briefing_cards_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_briefing_cards_session FOREIGN KEY (session_id) REFERENCES intake_sessions (id),
    CONSTRAINT fk_briefing_cards_parent FOREIGN KEY (parent_card_id) REFERENCES briefing_cards (id),
    CONSTRAINT ck_briefing_cards_status CHECK (status IN ('DRAFT', 'CONFIRMED')),
    CONSTRAINT ck_briefing_cards_patient_sex CHECK (patient_sex IN ('FEMALE', 'MALE', 'UNSPECIFIED')),
    CONSTRAINT ck_briefing_cards_onset_status CHECK (onset_status IN ('KNOWN', 'NONE', 'UNKNOWN')),
    CONSTRAINT ck_briefing_cards_pattern_status CHECK (pattern_status IN ('KNOWN', 'NONE', 'UNKNOWN')),
    CONSTRAINT ck_briefing_cards_site_status CHECK (site_status IN ('KNOWN', 'NONE', 'UNKNOWN')),
    CONSTRAINT ck_briefing_cards_medications_status CHECK (medications_status IN ('KNOWN', 'NONE', 'UNKNOWN')),
    CONSTRAINT ck_briefing_cards_allergies_status CHECK (allergies_status IN ('KNOWN', 'NONE', 'UNKNOWN'))
);

CREATE INDEX idx_intake_sessions_user ON intake_sessions (user_id);
CREATE INDEX idx_intake_session_sites_session ON intake_session_sites (session_id);
CREATE INDEX idx_intake_messages_session ON intake_messages (session_id);
CREATE INDEX idx_briefing_cards_user ON briefing_cards (user_id);
CREATE INDEX idx_briefing_cards_session ON briefing_cards (session_id);
