-- 진료 후 기록과 되묻기. 화면 S5.
--
-- 녹음은 저장하지 않는다. 기억 재구성 방식이라 오디오 컬럼 자체를 만들지 않는다.
-- 컬럼이 없으면 나중에 실수로 저장할 수도 없다.

-- 확정된 카드 하나에 기록 하나. clinic_name·what_was_done·result·prescription 이
-- 와이어프레임의 요약 카드에 그대로 찍힌다.
CREATE TABLE visit_records (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT        NOT NULL,
    card_id       BIGINT        NOT NULL,

    clinic_name   VARCHAR(60),
    visited_on    DATE          NOT NULL,
    what_was_done VARCHAR(200),
    result        VARCHAR(200),
    prescription  VARCHAR(200),

    -- 환자가 순서 없이 말한 원문. 위 항목은 여기서 정리해 낸 것이다.
    raw_note      VARCHAR(2000),

    created_at    TIMESTAMPTZ   NOT NULL,

    CONSTRAINT fk_visit_records_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_visit_records_card FOREIGN KEY (card_id) REFERENCES briefing_cards (id),
    CONSTRAINT uk_visit_records_card UNIQUE (card_id)
);

-- 이해 확인 문항. 와이어프레임 기준 3개 이내.
--
-- correct 가 null 이면 아직 답하지 않은 것이다.
-- 틀려도 넘어간다 — 시험이 아니라 이해 확인이다.
CREATE TABLE comprehension_checks (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_record_id  BIGINT       NOT NULL,
    seq              INTEGER      NOT NULL,
    question         VARCHAR(200) NOT NULL,
    expected_answer  VARCHAR(200) NOT NULL,
    user_answer      VARCHAR(500),
    correct          BOOLEAN,
    answered_at      TIMESTAMPTZ,

    CONSTRAINT fk_comprehension_checks_visit
        FOREIGN KEY (visit_record_id) REFERENCES visit_records (id),
    CONSTRAINT uk_comprehension_checks_visit_seq UNIQUE (visit_record_id, seq)
);

CREATE INDEX idx_visit_records_user ON visit_records (user_id);
CREATE INDEX idx_comprehension_checks_visit ON comprehension_checks (visit_record_id);
