-- 사진 첨부. 약봉투(S1)와 처방전·안내문(S5).
--
-- 바이트를 bytea 에 그대로 담는다. 배포 대상이 이미 백엔드·AI 둘인데
-- 스토리지까지 셋이 되는 것을 피한 결과다.
--
-- 소유는 nullable FK 두 개로 표현한다. 다형성(owner_type + owner_id)으로 하면
-- FK 를 걸 수 없어 원본이 지워져도 첨부가 남는다. 진료 데이터라 그게 안 된다.
CREATE TABLE attachments (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT       NOT NULL,

    -- 둘 중 정확히 하나만 채워진다.
    profile_id        BIGINT,
    visit_record_id   BIGINT,

    purpose           VARCHAR(20)  NOT NULL,
    content_type      VARCHAR(100) NOT NULL,
    original_filename VARCHAR(255),
    size_bytes        BIGINT       NOT NULL,
    data              BYTEA        NOT NULL,
    created_at        TIMESTAMPTZ  NOT NULL,

    CONSTRAINT fk_attachments_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_attachments_profile FOREIGN KEY (profile_id) REFERENCES health_profiles (id),
    CONSTRAINT fk_attachments_visit FOREIGN KEY (visit_record_id) REFERENCES visit_records (id),
    CONSTRAINT ck_attachments_purpose CHECK (purpose IN ('MEDICATION_BAG', 'PRESCRIPTION', 'GUIDE')),

    -- 소유가 없거나 둘 다인 첨부를 DB 가 막는다.
    CONSTRAINT ck_attachments_single_owner CHECK (
        (profile_id IS NOT NULL AND visit_record_id IS NULL)
        OR (profile_id IS NULL AND visit_record_id IS NOT NULL)
    )
);

CREATE INDEX idx_attachments_user ON attachments (user_id);
CREATE INDEX idx_attachments_profile ON attachments (profile_id);
CREATE INDEX idx_attachments_visit ON attachments (visit_record_id);
