-- 진료실 전달과 공유 링크. 화면 S4, S6.
--
-- QR 은 MVP 에서 뺐다. 관리자용 화면이 없어 찍을 주체가 없고,
-- 병원 대기실에서 신호가 약하면 그 자리에서 표시조차 안 된다.
-- 환자가 자기 화면을 의사에게 보여주는 형식으로 간다.

-- 전달 시각. S5 진료 후 기록 알림을 보낼 근거가 이 값이다.
-- 카드 하나가 여러 번 전달되는 시나리오가 MVP 에 없어 컬럼으로 둔다.
ALTER TABLE briefing_cards ADD COLUMN handed_off_at TIMESTAMPTZ;

-- 공유 링크. 인증 없이 열리므로 짧은 만료가 유일한 방어선이다.
--
-- JWT 무상태 대신 테이블을 쓰는 이유는 폐기 때문이다. 증상·복용약이 담긴
-- 링크라 잘못 보냈을 때 끌 수 있어야 하는데, JWT 는 만료까지 못 막는다.
CREATE TABLE share_links (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL,
    card_id    BIGINT      NOT NULL,

    -- 128비트 난수를 Base64URL 로 적은 22자.
    token      VARCHAR(64) NOT NULL,

    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,

    -- 마지막으로 열린 시각과 누적 횟수. 환자가 "누가 봤나" 를 확인하는 근거다.
    viewed_at  TIMESTAMPTZ,
    view_count INT         NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_share_links_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_share_links_card FOREIGN KEY (card_id) REFERENCES briefing_cards (id),
    CONSTRAINT uk_share_links_token UNIQUE (token)
);

CREATE INDEX idx_share_links_user ON share_links (user_id);
CREATE INDEX idx_share_links_card ON share_links (card_id);
