-- 진료 예정 일정. 화면 1r(캘린더) · 1n(홈).
--
-- visit_records 와 나눈다. 기록은 다녀온 뒤 남기고 일정은 가기 전에 만든다.
-- 생명주기가 반대라 한 테이블에 두면 "아직 안 간 기록"이라는 상태가 생긴다.
--
-- 병원명과 진료과를 나눠 둔다. 병원 검색(카카오 로컬)이 붙으면 place_name 과
-- category_name 이 따로 오므로 그대로 채울 수 있다. 화면의
-- "서울OO병원 내과 재진"은 앱이 조합한다.
CREATE TABLE appointments (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT      NOT NULL,

    -- 카드 없이도 일정을 만들 수 있다. 캘린더의 + 버튼이 그 경로다.
    card_id      BIGINT,

    clinic_name  VARCHAR(60) NOT NULL,
    department   VARCHAR(40),
    purpose      VARCHAR(60),

    -- 날짜만이 아니라 시각까지. 화면이 "오전 10:30"을 보여준다.
    scheduled_at TIMESTAMPTZ NOT NULL,

    status       VARCHAR(16) NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_appointments_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_appointments_card FOREIGN KEY (card_id) REFERENCES briefing_cards (id),
    CONSTRAINT ck_appointments_status CHECK (status IN ('SCHEDULED', 'DONE', 'CANCELED'))
);

-- 월별·일자별 조회와 "다가오는 일정"이 모두 이 조합을 탄다.
CREATE INDEX idx_appointments_user_scheduled ON appointments (user_id, scheduled_at);
CREATE INDEX idx_appointments_card ON appointments (card_id);
